-- AUTO-GENERATED. Apply scripts/schema.sql first.

-- banks
INSERT INTO banks (id, title, logo, swift_code, contact_first_name, contact_last_name, contact_email, contact_phone, endpoint_url, api_key, admin_username, admin_password, require_2fa) VALUES ('bank-1', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 'NATABSRPA12', 'Alice', 'Chen', 'alice@nationalagbank.com', '+12345678900', 'https://api.nationalagbank.com/services/loans/v1', 'nak-sk-live-abc123def456ghi789', 'loanadmin@nationalagbank.com', 'SecurePass2025!', TRUE);
INSERT INTO banks (id, title, logo, swift_code, contact_first_name, contact_last_name, contact_email, contact_phone, endpoint_url, api_key, admin_username, admin_password, require_2fa) VALUES ('bank-2', 'Rural Dev Bank', 'https://ui-avatars.com/api/?name=RD&background=9C27B0&color=fff&rounded=true&size=40', 'RUDEVBNK11', 'Robert', 'Kim', 'robert@ruraldevbank.com', '+71239871111', 'https://api.ruraldevbank.com/loans/v2', 'rdb-sk-live-xyz789abc123', 'admin@ruraldevbank.com', 'RuralDev2025!', FALSE);
INSERT INTO banks (id, title, logo, swift_code, contact_first_name, contact_last_name, contact_email, contact_phone, endpoint_url, api_key, admin_username, admin_password, require_2fa) VALUES ('bank-3', 'Zenith Bank', 'https://ui-avatars.com/api/?name=ZB&background=FF9800&color=fff&rounded=true&size=40', 'ZENITHBNK1', 'Frono', 'Jastica', 'fjastica@zenithbank.com', '+192837465', 'https://api.zenithbank.com/agri/v1', 'zb-sk-live-qwe456rty789', 'admin@zenithbank.com', 'Zenith2025!', TRUE);
INSERT INTO banks (id, title, logo, swift_code, contact_first_name, contact_last_name, contact_email, contact_phone, endpoint_url, api_key, admin_username, admin_password, require_2fa) VALUES ('bank-4', 'AgriFirst Bank', 'https://ui-avatars.com/api/?name=AF&background=4CAF50&color=fff&rounded=true&size=40', 'AGFIRST123', 'Sarah', 'Johnson', 'sarah@agrifirst.com', '+15551234567', 'https://api.agrifirst.com/lending/v1', 'af-sk-live-mno321pqr654', 'admin@agrifirst.com', 'AgriFi2025!', TRUE);
INSERT INTO banks (id, title, logo, swift_code, contact_first_name, contact_last_name, contact_email, contact_phone, endpoint_url, api_key, admin_username, admin_password, require_2fa) VALUES ('bank-5', 'Harvest Financial', 'https://ui-avatars.com/api/?name=HF&background=2196F3&color=fff&rounded=true&size=40', 'HARVFIN456', 'Michael', 'Brown', 'michael@harvestfin.com', '+15559876543', 'https://api.harvestfin.com/loans/v3', 'hf-sk-live-stu987vwx654', 'admin@harvestfin.com', 'Harvest2025!', FALSE);

-- cooperatives
INSERT INTO cooperatives (id, name, organisation_type, created_at) VALUES ('coop-1', 'Green Valley Cooperative', 'Cooperative', '2024-01-15');
INSERT INTO cooperatives (id, name, organisation_type, created_at) VALUES ('coop-2', 'Sunrise Farmers Cooperative', 'Cooperative', '2024-03-22');
INSERT INTO cooperatives (id, name, organisation_type, created_at) VALUES ('coop-3', 'Highland Growers Association', 'Cooperative', '2024-06-10');
INSERT INTO cooperatives (id, name, organisation_type, created_at) VALUES ('coop-4', 'Coastal Agriculture Cooperative', 'Cooperative', '2024-08-05');

-- auth_users (bcrypt)
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('1', 'Super Admin', 'superadmin@dimitra.io', '$2a$10$OwfDONgsDcuf8rrnT9an5.VIUQQWUM2PhZNFn9y3Mt8q/26MdAlYe', 'Dimitra', 'Dimitra', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('2', 'Maria Santos', 'maria@greenvalley.coop', '$2a$10$2ltObrjivFs6dUYSN4EBeeCfI0VBJSbQASQvzKkoQFzfugRN059W.', 'Cooperative', 'Green Valley Cooperative', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('3', 'John Doe', 'john@sunrisefarmers.coop', '$2a$10$PDN7GQIY99x78OCuz8JwpOw370FPcPsgtsdKzjUQieHITyhy71jN6', 'Cooperative', 'Sunrise Farmers Cooperative', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('4', 'Alice Chen', 'alice@nationalagbank.com', '$2a$10$b9A3E1/a1FQg8eDI5eCYXuk93iIuM0SIUWLwM38y2zPehA8HJhlZ6', 'Bank', 'National Agricultural Bank', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('5', 'Robert Kim', 'robert@ruraldevbank.com', '$2a$10$EK12EXcLqqohY4K9i9Ku8u3RcbOetmoQudHkeB.NMWC0nC6zHowh2', 'Bank', 'Rural Development Bank', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('6', 'Denzel Kromo', 'denzel-kromo@gmail.com', '$2a$10$gOzUn8I0zHwgbnvQ/6Eb9uQsf9nC9ja/q0HM5eU9aCxPou5er/IUe', 'Farm', 'Groningen Farm', '');
INSERT INTO auth_users (id, name, email, password_hash, role, organisation, avatar) VALUES ('7', 'Cynthia Pawiro', 'cynthia-pawiro@gmail.com', '$2a$10$Br6HTH2loitAb6rFcABSUedm8WWmxRPZRexOmaIp1Veolznc9KIRi', 'Farm', 'Mariënburg Farm', '');

-- farms
INSERT INTO farms (id, name, country, province, village, address, size, owner_id) VALUES ('farm-1', 'Groningen Farm', 'Suriname', 'Saramacca', 'Groningen', '123 ABC Street', 138.11, '6');
INSERT INTO farms (id, name, country, province, village, address, size, owner_id) VALUES ('farm-2', 'Groningen Estate Saramacca', 'Suriname', 'Brokopondo', 'Brownsweg', '12456 Centre Way', 850, '6');
INSERT INTO farms (id, name, country, province, village, address, size, owner_id) VALUES ('farm-3', 'Groningen Kromo Suriname Tabletop Farm', 'Suriname', 'Saramacca', 'Groningen', '456 Hans Bröker Street', 91, '6');
INSERT INTO farms (id, name, country, province, village, address, size, owner_id) VALUES ('farm-4', 'Mariënburg Farm', 'Suriname', 'Commewijne', 'Mariënburg', '789 Plantation Road', 45.5, '7');

-- platform_users
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-1', 'Super Admin', 'superadmin@dimitra.io', 'Dimitra', 'org-dimitra', TRUE, '2024-01-01');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-2', 'Maria Santos', 'maria@greenvalley.coop', 'Green Valley Cooperative', 'coop-1', TRUE, '2024-01-15');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-3', 'John Doe', 'john@sunrisefarmers.coop', 'Sunrise Farmers Cooperative', 'coop-2', TRUE, '2024-02-10');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-4', 'Alice Chen', 'alice@nationalagbank.com', 'National Agricultural Bank', 'bank-1', TRUE, '2024-03-05');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-5', 'Robert Kim', 'robert@ruraldevbank.com', 'Rural Development Bank', 'bank-2', TRUE, '2024-04-20');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-6', 'Denzel Kromo', 'denzel-kromo@gmail.com', 'Groningen Farm', 'farm-1', TRUE, '2024-05-15');
INSERT INTO platform_users (id, name, email, organisation, organisation_id, active, created_at) VALUES ('pu-7', 'Cynthia Pawiro', 'cynthia-pawiro@gmail.com', 'Mariënburg Farm', 'farm-4', TRUE, '2024-06-01');

-- loan_programs
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'coop-1', 'bank-1', 'Active', 'USD', 5000, 50000, 18, 5.9, 'Input Finance', 3, '["Coffee","Cacao"]'::jsonb, 'Indonesia', '["East Java","West Java"]'::jsonb, 'A comprehensive loan program designed to support smallholder farmers in accessing quality agricultural inputs including seeds, fertilizers, and crop protection products.', '2025-12-31', 'Monthly', 'Applicants must be registered members of Green Valley Cooperative with at least 1 year of membership. Farm must be at least 0.5 hectares. Valid national ID required.', '["Cooperative Review","Bank Assessment","Document Verification","Approval Decision"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-2', 'Green Valley Coop Zenith Bank Loan Program', 'https://ui-avatars.com/api/?name=GZ&background=009688&color=fff&rounded=true&size=40', 'coop-1', 'bank-3', 'Active', 'USD', 2000, 30000, 12, 6.5, 'Equipment Finance', 2, '["Rice","Corn"]'::jsonb, 'Indonesia', '["Central Java","East Java"]'::jsonb, 'Equipment financing program to help farmers invest in modern agricultural equipment and machinery for improved productivity.', '2025-11-30', 'Monthly', 'Must provide proof of farm ownership or long-term lease agreement. Minimum 2 years farming experience required.', '["Cooperative Review","Equipment Assessment","Bank Review","Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-3', 'Sunrise Farmers Coop - Rural Dev Loan Program', 'https://ui-avatars.com/api/?name=SF&background=E91E63&color=fff&rounded=true&size=40', 'coop-2', 'bank-2', 'Active', 'USD', 3000, 40000, 24, 5.5, 'Working Capital', 4, '["Coffee","Tea"]'::jsonb, 'Suriname', '["Paramaribo","Saramacca"]'::jsonb, 'Working capital loans for seasonal farming operations, covering labor costs, transport, and post-harvest handling.', '2025-12-15', 'Quarterly', 'Must be an active member of Sunrise Farmers Cooperative. Clean credit history required.', '["Application Review","Field Visit","Bank Assessment","Final Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-4', 'National Ag Bank - Direct Farm Loan Program', 'https://ui-avatars.com/api/?name=NF&background=3F51B5&color=fff&rounded=true&size=40', 'coop-1', 'bank-1', 'Active', 'USD', 10000, 100000, 36, 4.5, 'Land Development', 6, '["Palm Oil","Rubber"]'::jsonb, 'Indonesia', '["Sumatra","Kalimantan"]'::jsonb, 'Large-scale financing for land development and plantation establishment projects.', '2026-03-31', 'Monthly', 'Minimum 5 hectares of land. Environmental impact assessment required. Must have existing farming operation.', '["Application Submission","Environmental Review","Financial Assessment","Board Approval","Disbursement"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-5', 'The Best Loan Program', 'https://ui-avatars.com/api/?name=BL&background=FF5722&color=fff&rounded=true&size=40', 'coop-2', 'bank-2', 'Active', 'USD', 1000, 20000, 12, 7, 'Input Finance', 2, '["Vegetables","Fruits"]'::jsonb, 'Suriname', '["Nickerie","Coronie"]'::jsonb, 'Affordable microloans for small-scale farmers focusing on vegetable and fruit production.', '2025-10-31', 'Monthly', 'Open to all registered farmers with valid identification.', '["Cooperative Review","Bank Assessment","Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-6', 'National Ag Bank - Direct Farm Loan Program II', 'https://ui-avatars.com/api/?name=N2&background=607D8B&color=fff&rounded=true&size=40', 'coop-1', 'bank-1', 'Active', 'USD', 5000, 75000, 24, 5.2, 'Input Finance', 3, '["Coffee","Cacao","Vanilla"]'::jsonb, 'Indonesia', '["Bali","Lombok"]'::jsonb, 'Second phase of the direct farm loan program with improved terms and wider crop coverage.', '2026-06-30', 'Monthly', 'Must have completed at least one loan cycle successfully. Minimum 1 hectare.', '["Cooperative Review","Bank Assessment","Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-7', 'Sunrise Farmers Coop - Zenith Bank Loan Program', 'https://ui-avatars.com/api/?name=SZ&background=795548&color=fff&rounded=true&size=40', 'coop-2', 'bank-3', 'Active', 'USD', 2500, 35000, 18, 6, 'Working Capital', 3, '["Rice","Soybean"]'::jsonb, 'Suriname', '["Wanica","Commewijne"]'::jsonb, 'Working capital program for rice and soybean farmers in partnership with Zenith Bank.', '2025-12-31', 'Monthly', 'Active cooperative membership required. Must demonstrate previous farming experience.', '["Cooperative Review","Bank Assessment","Approval Decision"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-8', 'Zenith Direct Bank Ag Loan Program', 'https://ui-avatars.com/api/?name=ZD&background=00BCD4&color=fff&rounded=true&size=40', 'coop-1', 'bank-3', 'Active', 'USD', 4000, 45000, 15, 5.8, 'Equipment Finance', 2, '["Coffee"]'::jsonb, 'Indonesia', '["East Java"]'::jsonb, 'Direct agricultural equipment financing through Zenith Bank for coffee farmers.', '2025-11-30', 'Monthly', 'Coffee farming experience required. Must have land title or lease agreement.', '["Application","Equipment Verification","Bank Review","Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-9', 'Moon-Shot Cooperative Loan Program', 'https://ui-avatars.com/api/?name=MS&background=9C27B0&color=fff&rounded=true&size=40', 'coop-2', 'bank-2', 'Active', 'USD', 8000, 60000, 30, 4.9, 'Land Development', 5, '["Cassava","Plantain"]'::jsonb, 'Suriname', '["Brokopondo","Sipaliwini"]'::jsonb, 'Ambitious land development program for underserved rural communities.', '2026-01-31', 'Quarterly', 'Priority given to first-time borrowers in rural areas. Community endorsement required.', '["Community Review","Cooperative Assessment","Bank Evaluation","Approval"]'::jsonb);
INSERT INTO loan_programs (id, title, logo, cooperative_id, bank_id, status, currency, loan_amount_min, loan_amount_max, term_months, interest_rate, type_of_financing, grace_period_months, crops, country, regions, description, application_deadline, payment_frequency, conditions_requirements, application_process) VALUES ('lp-10', 'Green Valley Coop & Zenith Bank Super Loans Program', 'https://ui-avatars.com/api/?name=GS&background=F44336&color=fff&rounded=true&size=40', 'coop-1', 'bank-3', 'Active', 'USD', 15000, 150000, 48, 4.2, 'Comprehensive Farm Finance', 6, '["Coffee","Cacao","Pepper"]'::jsonb, 'Indonesia', '["East Java","West Java","Central Java"]'::jsonb, 'Premium comprehensive financing package for established farming operations seeking expansion.', '2026-06-30', 'Monthly', 'Minimum 3 years cooperative membership. Proven track record of successful harvests. Minimum 5 hectares.', '["Cooperative Review","Financial Analysis","Bank Assessment","Board Approval","Contract Signing"]'::jsonb);

-- loan_applications + children
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-013', '2026-01-15', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-10', 'Green Valley Coop & Zenith Bank Super Loans Program', 'https://ui-avatars.com/api/?name=GS&background=F44336&color=fff&rounded=true&size=40', 'Zenith Bank', 'https://ui-avatars.com/api/?name=ZB&background=FF9800&color=fff&rounded=true&size=40', 9800, 'USD', 'Pending', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"2.5 tons/hectare","confidence":85},"loanSuitability":{"rating":"Good","notes":"Farm has consistent yield history and good soil quality."},"soilAnalysis":{"ph":6.5,"organicMatter":3.2,"classification":"Loamy"}}'::jsonb, '{"loanPurpose":"The loan will help purchase modern irrigation equipment and high-yield seed varieties, increasing crop output by an estimated 30%.","comments":"I have been farming for over 15 years and have a strong track record of repaying previous agricultural loans on time.","landOwnershipProof":"Title deed registered under national registry #LR-2015-4521"}'::jsonb, '[{"name":"Land_Title_Deed.pdf","type":"pdf"},{"name":"Survey_Report.pdf","type":"pdf"},{"name":"Farm_Boundaries_2025.pdf","type":"pdf"}]'::jsonb, '{"totalAmount":9800,"interestRate":4.2,"installments":18,"gracePeriod":3,"firstDisbursement":"2026-02-01"}'::jsonb);
INSERT INTO disbursement_schedule (application_id, number, amount, date, transaction_id, status) VALUES ('APP-2026-013', 1, 4900, '2026-02-01', 'TXN-D001', 'Pending');
INSERT INTO disbursement_schedule (application_id, number, amount, date, transaction_id, status) VALUES ('APP-2026-013', 2, 4900, '2026-05-01', 'TXN-D002', 'Pending');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-013', 1, '2026-05-01', 544.44, 34.3, 578.74, 'TXN-R001', 'Pending');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-013', 2, '2026-06-01', 544.44, 32.4, 576.84, 'TXN-R002', 'Pending');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-013', 3, '2026-07-01', 544.44, 30.5, 574.94, 'TXN-R003', 'Pending');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-013', 'Admin', 'Status change', '2026-03-22 09:11', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-013', 'Admin', 'Review', '2026-03-22 12:00', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-013', 'Reviewer', 'Status change', '2026-03-25 14:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-012', '2026-01-10', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 15000, 'USD', 'Approved', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"3.0 tons/hectare","confidence":90},"loanSuitability":{"rating":"Excellent","notes":"Strong financial history and excellent farm management."},"soilAnalysis":{"ph":6.8,"organicMatter":3.5,"classification":"Clay Loam"}}'::jsonb, '{"loanPurpose":"Expanding coffee plantation by 10 hectares with improved varieties.","comments":"Experienced farmer with 15+ years of coffee cultivation.","landOwnershipProof":"Title deed #LR-2015-4521"}'::jsonb, '[{"name":"Land_Title_Deed.pdf","type":"pdf"},{"name":"Business_Plan.pdf","type":"pdf"}]'::jsonb, '{"totalAmount":15000,"interestRate":5.9,"installments":18,"gracePeriod":3,"firstDisbursement":"2026-02-01"}'::jsonb);
INSERT INTO disbursement_schedule (application_id, number, amount, date, transaction_id, status) VALUES ('APP-2026-012', 1, 7500, '2026-02-01', 'TXN-D101', 'Completed');
INSERT INTO disbursement_schedule (application_id, number, amount, date, transaction_id, status) VALUES ('APP-2026-012', 2, 7500, '2026-05-01', 'TXN-D102', 'Pending');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-012', 1, '2026-05-01', 833.33, 73.75, 907.08, 'TXN-R101', 'Pending');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-012', 2, '2026-06-01', 833.33, 69.65, 902.98, 'TXN-R102', 'Pending');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-012', 'Admin', 'Application submitted by farmer', '2026-01-10 09:00', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-012', 'Admin', 'Application approved', '2026-01-25 14:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-011', '2026-01-08', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 8500, 'USD', 'Waiting Signatures', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"2.8 tons/hectare","confidence":82},"loanSuitability":{"rating":"Good","notes":"Meets all basic requirements."},"soilAnalysis":{"ph":6.3,"organicMatter":2.9,"classification":"Sandy Loam"}}'::jsonb, '{"loanPurpose":"Purchase fertilizers and pesticides for the upcoming season.","comments":"Need timely disbursement before planting season.","landOwnershipProof":"Lease agreement #LA-2023-891"}'::jsonb, '[{"name":"Lease_Agreement.pdf","type":"pdf"}]'::jsonb, NULL);
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-011', 'Admin', 'Application submitted', '2026-01-08 11:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-005', '2025-12-20', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 12000, 'USD', 'Sent to Bank', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"2.2 tons/hectare","confidence":78},"loanSuitability":{"rating":"Moderate","notes":"Acceptable risk level."},"soilAnalysis":{"ph":6,"organicMatter":2.5,"classification":"Loamy"}}'::jsonb, '{"loanPurpose":"Invest in drip irrigation system for water efficiency.","comments":"Current irrigation is flood-based and inefficient.","landOwnershipProof":"Title deed #LR-2018-7892"}'::jsonb, '[{"name":"Irrigation_Plan.pdf","type":"pdf"},{"name":"Cost_Estimate.pdf","type":"pdf"}]'::jsonb, NULL);
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-005', 'Admin', 'Application submitted', '2025-12-20 10:00', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-005', 'Cooperative', 'Sent to bank', '2025-12-28 15:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-003', '2025-12-15', 'Cynthia Pawiro', 'cynthia-pawiro@gmail.com', '+597 8654321', '2536148', 'lp-3', 'Sunrise Farmers Coop - Rural Dev Loan Program', 'https://ui-avatars.com/api/?name=SF&background=E91E63&color=fff&rounded=true&size=40', 'Rural Dev Bank', 'https://ui-avatars.com/api/?name=RD&background=9C27B0&color=fff&rounded=true&size=40', 20000, 'USD', 'Rejected', '{"name":"Mariënburg Farm","country":"Suriname","province":"Commewijne","village":"Mariënburg","size":45.5}'::jsonb, '{"yieldPrediction":{"predictedYield":"1.8 tons/hectare","confidence":65},"loanSuitability":{"rating":"Poor","notes":"Insufficient collateral and inconsistent yield history."},"soilAnalysis":{"ph":5.5,"organicMatter":1.8,"classification":"Sandy"}}'::jsonb, '{"loanPurpose":"Expand tea cultivation area.","comments":"First time applying for agricultural loan.","landOwnershipProof":"Pending title deed application"}'::jsonb, '[{"name":"ID_Document.img","type":"img"}]'::jsonb, NULL);
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-003', 'Admin', 'Application submitted', '2025-12-15 09:30', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-003', 'Bank', 'Application rejected', '2025-12-22 16:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-002', '2025-12-10', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 5890, 'USD', 'Pending', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"2.4 tons/hectare","confidence":80},"loanSuitability":{"rating":"Good","notes":"Standard application."},"soilAnalysis":{"ph":6.4,"organicMatter":3,"classification":"Loamy"}}'::jsonb, '{"loanPurpose":"Purchase seeds and basic farming tools.","comments":"Routine seasonal financing.","landOwnershipProof":"Title deed #LR-2015-4521"}'::jsonb, '[{"name":"Application_Form.pdf","type":"pdf"}]'::jsonb, NULL);
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-002', 'Admin', 'Application submitted', '2025-12-10 08:00', '192.168.1.10');
INSERT INTO loan_applications (id, submission_date, applicant_name, applicant_email, applicant_phone, applicant_national_id, loan_program_id, loan_program_title, loan_program_logo, bank_name, bank_logo, amount, currency, status, farm, farm_reports, additional_questions, documents, loan_details) VALUES ('APP-2026-001', '2025-12-05', 'Denzel Kromo', 'denzel-kromo@gmail.com', '+597 8123456', '1425362', 'lp-1', 'Green Valley Coop - National Ag Loan Program', 'https://ui-avatars.com/api/?name=GV&background=4CAF50&color=fff&rounded=true&size=40', 'National Ag Bank', 'https://ui-avatars.com/api/?name=NA&background=FFD700&color=000&rounded=true&size=40', 3850, 'USD', 'Approved', '{"name":"Groningen Farm","country":"Suriname","province":"Saramacca","village":"Groningen","size":138.11}'::jsonb, '{"yieldPrediction":{"predictedYield":"2.6 tons/hectare","confidence":88},"loanSuitability":{"rating":"Excellent","notes":"Repeat borrower with perfect record."},"soilAnalysis":{"ph":6.7,"organicMatter":3.4,"classification":"Clay Loam"}}'::jsonb, '{"loanPurpose":"Seasonal input financing for coffee production.","comments":"Third successful loan cycle.","landOwnershipProof":"Title deed #LR-2015-4521"}'::jsonb, '[{"name":"Previous_Loan_Statement.pdf","type":"pdf"}]'::jsonb, '{"totalAmount":3850,"interestRate":5.9,"installments":12,"gracePeriod":2,"firstDisbursement":"2025-12-15"}'::jsonb);
INSERT INTO disbursement_schedule (application_id, number, amount, date, transaction_id, status) VALUES ('APP-2026-001', 1, 3850, '2025-12-15', 'TXN-D301', 'Completed');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-001', 1, '2026-02-15', 320.83, 18.93, 339.76, 'TXN-R301', 'Completed');
INSERT INTO repayment_schedule (application_id, installment, due_date, principal, interest, total, transaction_id, status) VALUES ('APP-2026-001', 2, '2026-03-15', 320.83, 17.35, 338.18, 'TXN-R302', 'Pending');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-001', 'Admin', 'Application submitted', '2025-12-05 09:00', '192.168.1.10');
INSERT INTO activity_log (application_id, "user", action, date_time, ip_address) VALUES ('APP-2026-001', 'Bank', 'Application approved', '2025-12-12 14:00', '192.168.1.10');

-- application_form_fields
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('group-general', NULL, 'General Information', 'Group', FALSE, NULL, 0);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('customer-type', 'group-general', 'Customer Type', 'Dropdown', TRUE, '[{"label":"Individual","value":"individual"},{"label":"Business","value":"business"},{"label":"Cooperative Member","value":"cooperative_member"}]'::jsonb, 1);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('finance-type', 'group-general', 'Type of Financing', 'Dropdown', TRUE, '[{"label":"Input Finance","value":"input_finance"},{"label":"Equipment Finance","value":"equipment_finance"},{"label":"Working Capital","value":"working_capital"},{"label":"Land Development","value":"land_development"}]'::jsonb, 2);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('loan-amount', 'group-general', 'Requested Loan Amount', 'Text Field Numeric', TRUE, NULL, 3);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('loan-purpose', 'group-general', 'Purpose of Loan', 'Text Field', TRUE, NULL, 4);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('group-applicant', NULL, 'Applicant Details', 'Group', FALSE, NULL, 5);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('full-name', 'group-applicant', 'Full Name', 'Text Field', TRUE, NULL, 6);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('national-id', 'group-applicant', 'National ID Number', 'Text Field', TRUE, NULL, 7);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('phone', 'group-applicant', 'Phone Number', 'Text Field', TRUE, NULL, 8);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('email', 'group-applicant', 'Email Address', 'Text Field', TRUE, NULL, 9);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('group-address', NULL, 'Address Details', 'Group', FALSE, NULL, 10);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('country', 'group-address', 'Country', 'Dropdown', TRUE, '[{"label":"Indonesia","value":"indonesia"},{"label":"Suriname","value":"suriname"},{"label":"Netherlands","value":"netherlands"}]'::jsonb, 11);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('province', 'group-address', 'Province / State', 'Text Field', TRUE, NULL, 12);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('city', 'group-address', 'City / Village', 'Text Field', TRUE, NULL, 13);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('street', 'group-address', 'Street Address', 'Text Field', FALSE, NULL, 14);
INSERT INTO application_form_fields (id, parent_id, label, type, mandatory, subdata, sort_order) VALUES ('supporting-docs', NULL, 'Supporting Documents', 'Attach File', FALSE, NULL, 15);

-- dashboard_snapshots
INSERT INTO dashboard_snapshots (period, data) VALUES ('month', '{"loanApplicationsChart":{"months":["January","February","March","April","May","June","July","August","September","October","November","December"],"approved":[5,8,6,4,7,18,43,12,8,6,5,7],"pending":[3,5,4,3,5,12,28,10,6,4,3,4],"waiting":[2,3,2,2,3,8,18,6,4,2,2,3],"rejected":[1,2,1,1,2,5,6,3,2,1,1,2]},"processingTimeChart":{"months":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],"days":[35,30,28,32,25,22,20,23,26,24,21,19]},"applicationsByRegion":{"regions":["Montesino","Kerala","Kuari"],"counts":[85,65,42]},"stats":{"avgProcessingTime":{"value":23,"unit":"days","trend":15},"totalApplications":{"value":132,"trend":10},"approvalPercentage":{"value":40,"unit":"%","trend":-10}}}'::jsonb);
INSERT INTO dashboard_snapshots (period, data) VALUES ('quarter', '{"loanApplicationsChart":{"months":["Q1","Q2","Q3","Q4"],"approved":[19,21,38,18],"pending":[12,16,31,11],"waiting":[7,10,18,7],"rejected":[4,6,10,4]},"processingTimeChart":{"months":["Q1","Q2","Q3","Q4"],"days":[28,20,29,20]},"applicationsByRegion":{"regions":["Montesino","Kerala","Kuari"],"counts":[210,180,140]},"stats":{"avgProcessingTime":{"value":24,"unit":"days","trend":8},"totalApplications":{"value":396,"trend":15},"approvalPercentage":{"value":45,"unit":"%","trend":5}}}'::jsonb);
INSERT INTO dashboard_snapshots (period, data) VALUES ('year', '{"loanApplicationsChart":{"months":["2022","2023","2024","2025"],"approved":[65,82,96,106],"pending":[40,55,70,65],"waiting":[25,32,42,38],"rejected":[15,20,24,22]},"processingTimeChart":{"months":["2022","2023","2024","2025"],"days":[35,30,26,23]},"applicationsByRegion":{"regions":["Montesino","Kerala","Kuari"],"counts":[520,440,380]},"stats":{"avgProcessingTime":{"value":28,"unit":"days","trend":-12},"totalApplications":{"value":1340,"trend":22},"approvalPercentage":{"value":42,"unit":"%","trend":3}}}'::jsonb);
